---
title: "`lidR`: (A workshop for) Airborne LiDAR Data Manipulation and Visualization for Forestry Applications"
author: "Tristan R.H. Goodbody, Jean-Romain Roussel"
institute: "University of British Columbia, Université Laval, Ministère des Forêts, de la Faune et des Parcs (Québec)"
date: 2023-09-05
---

```{r, echo = FALSE}
library(rgl)

r3dDefaults = rgl::r3dDefaults
m = structure(c(0.921, -0.146, 0.362, 0, 0.386, 0.482, -0.787, 0, 
                -0.06, 0.864, 0.5, 0, 0, 0, 0, 1), .Dim = c(4L, 4L))
r3dDefaults$FOV = 50
r3dDefaults$userMatrix = m
r3dDefaults$zoom = 0.75

knitr::opts_chunk$set(
  comment =  "#>", 
  collapse = TRUE,
  fig.align = "center")

rgl::setupKnitr(autoprint = TRUE) 
options(lidR.progress = FALSE)

```

## People

**Presenter:** Tristan Goodbody (UBC)

**Assistants:**

-   Alexandre Morin-Bernard (Laval)

-   Leanna Stackhouse (UBC)

-   Liam Irwin (UBC)

## Materials

[This repository](https://github.com/tgoodbody/lidRtutorial) contains the material for a \~3 hour `lidR` tutorial workshop. You should install the material on your own machine from [this repository](https://github.com/tgoodbody/lidRtutorial). It contains the code, the shapefiles and point-clouds we will use. The workshop intends to:

-   Present an overview of what can be done with `lidR`
-   Give users an understanding of how `lidR` may fit their needs
-   Exercises will be done depending on available time - users are encouraged to work on these after the workshop!

Find the code, exercises, and solutions used in the `.\R` directory.

## Requirements

### R version and Rstudio

-   You need to install a recent version of `R` i.e. `R 4.0.x` or newer.
-   We will work with [Rstudio](https://www.rstudio.com/). This IDE is not mandatory to follow the workshop but is highly recommended.

### R Packages

You need to install the `lidR` package in its latest version (v \>= 4.0.0).

``` r
install.packages("lidR")
```

To run all code in the tutorial yourself, you will need to install the following packages. You can use `lidR` without them, however.

``` r
libs <- c("geometry","viridis","future","sf","gstat","terra","mapview","mapedit","concaveman","microbenchmark")

install.packages(libs)
```

## Estimated schedule {.smaller}

-   Introduction and set-up (09:00)
-   Read LAS and LAZ files (09:15)
-   Spatial queries (09:35)
-   Area-Based Approach (09:45)
-   Canopy Height Model (10:00)
-   Digital Terrain Model (10:10)

--- Break until 10:30 ---

-   Individual tree segmentation (10:30)
-   File collection processing engine (basic) (11:00)
-   File collection processing engine (advanced) (11:30)

## Resources

We strongly recommend having the following resources available to you:

-   The [`lidR` official documentation](https://cran.r-project.org/web/packages/lidR/lidR.pdf)
-   The [lidRbook](https://r-lidar.github.io/lidRbook/) of tutorials

When working on exercises:

-   [Stack Exchange with the `lidR` tag](https://gis.stackexchange.com/questions/tagged/lidr)

## `lidR`

`lidR` is an R package to work with LiDAR data developed at Laval University (Québec). It was developed & continues to be maintained by [Jean-Romain Roussel](https://github.com/Jean-Romain) and was made possible between:

-   2015 and 2018 thanks to the financial support of the AWARE project NSERC CRDPJ 462973-14; grantee Prof. Nicholas C. Coops.

-   2018 and 2021 thanks to the financial support of the Ministère des Forêts, de la Faune et des Parcs (Québec).

The current release version of `lidR` can be found on [CRAN](https://cran.r-project.org/web/packages/lidR/) and source code is hosted on [GitHub](https://github.com/r-lidar/lidR).
